### ISSUE TITLE
qr-code is not working on IE ,safari & Mozilla browser.

### ISSUE THREAD

**Issue by Rajfkvp** [educastellano/qr-code#14]

**Comment by educastellano** [comment]
Are you using the Web Components Polyfill? https://www.npmjs.com/package/webcomponents.js

**Comment by btopro** [comment]
Make sure you have the FULL polyfill and not the -lite one. When using this if I used the full polyfill which emulates shadowdom then it works. If I just do lite (which is only shadycss emulation) then it bricks since qr.js has early in its life cycle to attach a shadowroot

**Comment by educastellano** [comment]
It seems this is due to the deprecated `document.registerElement()`. Closing this since it's related to #15
