### ISSUE TITLE
Document.registerElement()

### ISSUE THREAD

**Issue by DamandeepS** [educastellano/qr-code#15]
#### Deprecated

This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Avoid using it and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement

**Comment by educastellano** [comment]
@DamandeepS Thanks for reporting this. 

I've started a new branch re-writing it in es6 with all the new syntax, but I have some problems transpiling it to es5 to keep support for older browsers. I'll merge it as soon as I fix that.

**Comment by educastellano** [comment]
Resolved and published @1.0.0 🎉👍
