### ISSUE TITLE
Cannot control size with height/width CSS attributes

### ISSUE THREAD

**Issue by pietrorea** [educastellano/qr-code#17]
Hello, I tried to control the size of the QR code component like this:

```
qr-code {
  width: 10rem;
  height: 10rem;
}
```

but this doesn't resize the actual QR code:

<img width="170" alt="Screen Shot 2022-02-16 at 4 44 54 PM" src="https://user-images.githubusercontent.com/1264371/154363118-0a3f043a-0891-423f-ae90-c512fc795772.png">

is the only way to control the size `modulesize`?

**Comment by educastellano** [comment]
Yea, it's like that now... We could add a `innerStyle` prop which passes the style down to the inner element. Feel free to send me a PR.
