### ISSUE TITLE
Some Questions About Your QR

### ISSUE THREAD

**Issue by vdanelia** [educastellano/qr-code#8]
Hello Eduard, I found your QR Code JS and testing it
Working very smoothly

I have a question:

Q.1

How to add additional info to QR Code for example:
I need These Information:
My URL:
My Mail:
My Phone:
So That I Manage what values to add or remove

Q.2 How to specify QR Colors

And Last Hard Question about URL

How to make script in such case that the QR code automatically detect the url address of a page where it is inserted?

(I want to attach qrcode to a product books page and i want that qr automatically detect the url)

Thank you in advanced

**Comment by educastellano** [comment]
**Q1**
You can add any information you want in a QR code. Try to use a `<textarea>` if you need break lines.

**Q2**
There is no support for colors right now. You can fork+PR me, or you can do this little hack that it just occurred to me, creating the component in HTML format:

``` js
var tds = document.querySelector('qr-code').shadowRoot.querySelectorAll('table td')
for (var i=0; i<tds.length; i++) {
    if(tds[i].style.background) {
        tds[i].style.background='red'
    }
}
```

**Question about URL**

Just define the component:

``` html
<qr-code data=""></qr-code>
```

And set the data attribute by code:

``` js
document.querySelector('qr-code').data = window.location.href
```

**Comment by vdanelia** [comment]
Thank You I'll test it :)

**Comment by educastellano** [comment]
:+1:
